### ISSUE TITLE
Ignoring ZeroTier variables.

### ISSUE THREAD

**Issue by i2chris** [m4rcu5nl/ansible-role-zerotier#34]
This ansible module is ignoring my variables 'zerotier_member_ip_assignments' and 'zerotier_member_description'.  They aren't being set in the zerotier web ui.   The IP is auto and there is no description.

Am I doing something wrong here?  I'm new to ansible, so I probably am :-) 

Playbook:
```
- hosts: pis
  remote_user: pi
  vars:
      zerotier_network_id: ...
  roles:
      - { role: m4rcu5nl.zerotier-one, become: true }
```

Inventory:
```
[pis]
raspberry-1 zerotier_member_ip_assignments='["10.144.100.1"]'

[pis:vars]
zerotier_member_description='Rasberry Pi'
user_basedir=/home/pi
```
